import { NextResponse } from "next/server";
import { requireCurrentWorkspaceContext } from "@/lib/services/current-workspace";
import { auditEvent } from "@/lib/services/audit";
import { canViewInvoiceFeature, getInvoiceByIdForUser } from "@/lib/services/invoices";
import { calculateInvoiceTotals, formatCurrency, type InvoiceLineItemDraft } from "@/lib/invoice-calculations";
import { serverLog } from "@/lib/services/runtime-config";

function escapeHtml(value: string | null | undefined) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function safeDownloadName(value: string) {
  return value.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^-+|-+$/g, "") || "invoice";
}

function coerceLineItems(value: unknown): InvoiceLineItemDraft[] {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => ({
      description: typeof item === "object" && item && "description" in item ? String((item as { description?: string }).description || "") : "",
      quantity: typeof item === "object" && item && "quantity" in item ? Number((item as { quantity?: number }).quantity || 0) : 0,
      unitPriceCents: typeof item === "object" && item && "unitPriceCents" in item ? Number((item as { unitPriceCents?: number }).unitPriceCents || 0) : 0,
      gstRateBps: typeof item === "object" && item && "gstRateBps" in item ? Number((item as { gstRateBps?: number }).gstRateBps || 0) : 0,
      isTaxInclusive: typeof item === "object" && item && "isTaxInclusive" in item ? Boolean((item as { isTaxInclusive?: boolean }).isTaxInclusive) : false
    }))
    .filter((item) => item.description.trim());
}

function invoiceHtml(invoice: NonNullable<Awaited<ReturnType<typeof getInvoiceByIdForUser>>>) {
  const lineItems = coerceLineItems(invoice.lineItemsJson);
  const totals = calculateInvoiceTotals(lineItems, invoice.discountCents);
  const address = escapeHtml(invoice.clientAddress).replace(/\r?\n/g, "<br/>");
  const notes = escapeHtml(invoice.notes).replace(/\r?\n/g, "<br/>");
  const paymentInstructions = escapeHtml(invoice.paymentInstructions).replace(/\r?\n/g, "<br/>");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(invoice.invoiceNumber)}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #0f172a; }
    h1, h2, h3, p { margin: 0; }
    .header, .meta, .totals, .notes { margin-bottom: 24px; }
    .muted { color: #475569; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    th, td { border-bottom: 1px solid #e2e8f0; padding: 10px 8px; text-align: left; vertical-align: top; }
    th:last-child, td:last-child { text-align: right; }
    .totals-row { display: flex; justify-content: space-between; margin: 6px 0; }
    .total-strong { font-weight: 700; font-size: 18px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Invoice ${escapeHtml(invoice.invoiceNumber)}</h1>
    <p class="muted">Generated by Aria for operational billing support. Review required before external use.</p>
  </div>
  <div class="meta">
    <p><strong>Client:</strong> ${escapeHtml(invoice.clientName)}</p>
    <p><strong>Email:</strong> ${escapeHtml(invoice.clientEmail)}</p>
    <p><strong>Address:</strong><br/>${address || "Not provided"}</p>
    <p><strong>Issue date:</strong> ${new Date(invoice.issueDate).toLocaleDateString("en-AU")}</p>
    <p><strong>Due date:</strong> ${new Date(invoice.dueDate).toLocaleDateString("en-AU")}</p>
    <p><strong>Status:</strong> ${escapeHtml(invoice.status.replaceAll("_", " "))}</p>
  </div>
  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th>Qty</th>
        <th>Unit price</th>
        <th>GST</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      ${lineItems.map((item) => `
        <tr>
          <td>${escapeHtml(item.description)}</td>
          <td>${escapeHtml(String(item.quantity))}</td>
          <td>${escapeHtml(formatCurrency(item.unitPriceCents, invoice.currency))}</td>
          <td>${escapeHtml(`${(item.gstRateBps / 100).toFixed(1)}%`)}</td>
          <td>${escapeHtml(formatCurrency(item.quantity * item.unitPriceCents, invoice.currency))}</td>
        </tr>
      `).join("")}
    </tbody>
  </table>
  <div class="totals">
    <div class="totals-row"><span>Subtotal</span><span>${escapeHtml(formatCurrency(totals.subtotalCents, invoice.currency))}</span></div>
    <div class="totals-row"><span>GST</span><span>${escapeHtml(formatCurrency(totals.gstCents, invoice.currency))}</span></div>
    <div class="totals-row"><span>Discount</span><span>${escapeHtml(formatCurrency(totals.discountCents, invoice.currency))}</span></div>
    <div class="totals-row total-strong"><span>Total due</span><span>${escapeHtml(formatCurrency(totals.totalCents, invoice.currency))}</span></div>
  </div>
  <div class="notes">
    <p><strong>Notes</strong></p>
    <p>${notes || "None"}</p>
  </div>
  <div class="notes">
    <p><strong>Payment instructions</strong></p>
    <p>${paymentInstructions || "Not provided"}</p>
  </div>
</body>
</html>`;
}

export async function POST(_: Request, { params }: { params: { invoiceId: string } }) {
  try {
    const context = await requireCurrentWorkspaceContext();
    if (!canViewInvoiceFeature(context.user)) {
      return NextResponse.json({ error: "You do not have permission to download invoices." }, { status: 403 });
    }

    const invoice = await getInvoiceByIdForUser(context.workspace.id, params.invoiceId, context.user);
    if (!invoice) {
      return NextResponse.json({ error: "Invoice not found for this workspace scope." }, { status: 404 });
    }

    await auditEvent({
      workspaceId: context.workspace.id,
      userId: context.user.id,
      entityType: "Invoice",
      entityId: invoice.id,
      action: "invoice.downloaded"
    });

    return new NextResponse(invoiceHtml(invoice), {
      status: 200,
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${safeDownloadName(invoice.invoiceNumber)}.html"`,
        "Cache-Control": "private, no-store",
        "X-Content-Type-Options": "nosniff"
      }
    });
  } catch (error) {
    serverLog("invoice.download_error", { error: error instanceof Error ? error.message : String(error), invoiceId: params.invoiceId });
    return NextResponse.json({ error: "Unable to prepare invoice download right now." }, { status: 500 });
  }
}
