DO $$ BEGIN
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMPANY_OWNER';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMPANY_ADMIN';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ORGANISATION_ACCESS_ADMIN';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PRINCIPAL_REGISTERED_MIGRATION_AGENT';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SENIOR_MIGRATION_AGENT';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MIGRATION_AGENT';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CASE_MANAGER';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ADMIN_ASSISTANT';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CLIENT_REVIEW_COORDINATOR';
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE "UserStatus" AS ENUM ('INVITED', 'ACTIVE', 'DISABLED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE "UserVisibilityScope" AS ENUM ('ASSIGNED_ONLY', 'TEAM_OVERSIGHT', 'FIRM_WIDE');
EXCEPTION WHEN duplicate_object THEN null; END $$;

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS "jobTitle" TEXT,
  ADD COLUMN IF NOT EXISTS "notes" TEXT,
  ADD COLUMN IF NOT EXISTS "visibilityScope" "UserVisibilityScope" NOT NULL DEFAULT 'ASSIGNED_ONLY',
  ADD COLUMN IF NOT EXISTS "invitedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "lastActiveAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "deactivatedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "supervisorId" TEXT;

ALTER TABLE "Client"
  ADD COLUMN IF NOT EXISTS "assignedToUserId" TEXT;

DO $$ BEGIN
  ALTER TABLE "User"
    ADD CONSTRAINT "User_supervisorId_fkey"
    FOREIGN KEY ("supervisorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  ALTER TABLE "Client"
    ADD CONSTRAINT "Client_assignedToUserId_fkey"
    FOREIGN KEY ("assignedToUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE INDEX IF NOT EXISTS "User_workspaceId_role_status_idx" ON "User"("workspaceId", "role", "status");
CREATE INDEX IF NOT EXISTS "Client_assignedToUserId_idx" ON "Client"("assignedToUserId");
CREATE INDEX IF NOT EXISTS "User_supervisorId_idx" ON "User"("supervisorId");
